


// Generated by https://quicktype.io

import 'package:teslo_shop/features/auth/domain/domain.dart';

class ProductEntity {

  String id;
  String title;
  int price;
  String description;
  String slug;
  int stock;
  List<String> sizes;
  String gender;
  List<String> tags;
  List<String> images;
  UserEntity user;

  ProductEntity({
   required this.id,
   required this.title,
   required this.price,
   required this.description,
   required this.slug,
   required this.stock,
   required this.sizes,
   required this.gender,
   required this.tags,
   required this.images,
   required this.user,
  });
}

